name: alyarmok_hotel
description: "A new Flutter project."
 
 
publish_to: 'none'  

  
version: 1.0.0+1

environment:
  sdk: ^3.7.2

 
  
 
dependencies:
  flutter:
    sdk: flutter

     
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  http: ^1.3.0
  easy_localization: ^3.0.7+1
  image_network: ^2.6.0
  image_picker: ^1.1.2
  path: ^1.9.1
  file_picker: ^10.1.9
  http_parser: ^4.1.2

    

    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter_localizations:

   
       
   
  flutter_lints: ^5.0.0

 
 

 
flutter:

   
   
   
  uses-material-design: true

   
  assets:
    - assets/lang/ar.json
    - assets/lang/en.json
     
     

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
  #
   
   
